[package]
name = "GateVRClient"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.17"
cgmath = "0.18"
winit = "0.28"
env_logger = "0.10"
pollster = "0.2"
openxr = "0.19"
rust-embed = "6.6.0"
image = "0.24"
bytemuck = { version = "1.4", features = ["derive"] }
fbx = "0.2"